server:
  port: 8080
  
axon:
  serializer:
    general: jackson
  eventhandling:
    processors:
      "[summaryGroup]":
        mode: TRACKING
        threadCount: 1
        batchSize: 1

spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update       
    show-sql: true
  profiles:
    active:
    - command
    - query  